# Generated by Django 5.0.7 on 2024-09-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_uz', models.CharField(max_length=25, null=True)),
                ('name_ru', models.CharField(max_length=25, null=True)),
                ('slug', models.SlugField(max_length=25, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category/icons/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
