# Generated by Django 5.0.7 on 2024-09-12 11:59

import apps.companies.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_uz', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='discount/icon/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveIntegerField(editable=False, unique=True)),
                ('discount_type', models.PositiveSmallIntegerField(choices=[(1, 'STANDARD'), (2, 'FREE PRODUCT'), (3, 'QUANTITY DISCOUNT'), (4, 'SERVICE DISCOUNT')])),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('description_uz', models.TextField(max_length=1000, null=True)),
                ('description_ru', models.TextField(max_length=1000, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='discount/video/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), apps.companies.validators.validate_company_video_size])),
                ('available', models.PositiveIntegerField()),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.PositiveSmallIntegerField(choices=[(1, 'UZS'), (2, 'USD')], default=1)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'PROCESS'), (2, 'ACCEPTED'), (3, 'REJECTED')], default=1)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery', models.BooleanField(default=False)),
                ('installment', models.BooleanField(default=False)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_value_is_percent', models.BooleanField(default=False)),
                ('min_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bonus_quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bonus_discount_value', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonus_discount_value_is_percent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(blank=True, related_name='discounts', to='companies.filial')),
                ('category', models.ForeignKey(limit_choices_to={'parent__parent__isnull: False'}, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='categories.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='companies.company')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.servicediscount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='discount/image/%Y/%m/%d/')),
                ('ordering_number', models.PositiveIntegerField()),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
