# Generated by Django 5.0.7 on 2024-09-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='categories.category'),
        ),
    ]
